# Generated by Django 4.1.4 on 2023-02-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontemplate',
            name='connection_template_groups',
        ),
        migrations.DeleteModel(
            name='ConnectionGroup',
        ),
    ]
