# Generated by Django 4.1.7 on 2023-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='ssh_special_template',
            field=models.BooleanField(default=False, help_text='SSH special template.', verbose_name='Special template'),
        ),
    ]
