# Generated by Django 4.1.4 on 2023-03-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_remove_connectiontemplate_http_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontemplate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='modelgrouptemplate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='modeltemplate',
            name='slug',
        ),
    ]
