# Generated by Django 4.1.4 on 2023-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_remove_connectiontemplate_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontemplate',
            name='ssh_special_template',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='Special template'),
        ),
        migrations.AddField(
            model_name='connectiontemplate',
            name='ssh_vrf_template',
            field=models.BooleanField(default=False, help_text='VRF cli command template.', verbose_name='VRF template'),
        ),
        migrations.AddField(
            model_name='connectiontemplate',
            name='xxx',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='Xxx'),
        ),
    ]
