# Generated by Django 4.1.7 on 2023-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_alter_connectiontemplate_ssh_special_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='http_response_type',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'List'), (2, 'Dict'), (3, 'String')], default=0, help_text='Type of HTTP(S) response. If the host sends a response of a different type than specified, the response will be treated as invalid.', verbose_name='HTTP(s) type of response'),
        ),
    ]
