# Generated by Django 4.1.4 on 2023-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_host_credential_alter_host_platform'),
        ('connector', '0004_connectiontemplate_ssh_special_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontemplate',
            old_name='platform',
            new_name='platforms',
        ),
        migrations.RemoveField(
            model_name='connectiontemplate',
            name='xxx',
        ),
    ]
