# Generated by Django 4.1.4 on 2023-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_host_certificate_check'),
        ('connector', '0005_remove_connectiontemplate_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='platforms',
            field=models.ManyToManyField(help_text='One or more platform(s) can be added to the connection template. To associate the template with the appropriate platform(s). Template execution will only be available to hosts belonging to the specified platform.', to='inventory.platform', verbose_name='Platform'),
        ),
    ]
