# Generated by Django 4.1.4 on 2023-03-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_alter_connectiontemplate_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='datagrouptemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='datatemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='modelgrouptemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='modeltemplate',
            name='is_deleted',
        ),
    ]
