# Generated by Django 4.1.7 on 2023-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_remove_connectiontemplate_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontemplate',
            name='response_type',
            field=models.IntegerField(choices=[(1, 'Bool'), (2, 'List'), (3, 'Dict'), (4, 'String')], default=1, help_text='Xxx.', verbose_name='Type of response'),
        ),
    ]
