# Generated by Django 4.1.7 on 2023-03-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_connectiontemplate_response_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontemplate',
            name='sfm_expression',
        ),
    ]
