# Generated by Django 4.1.7 on 2023-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0010_connectiontemplate_slug_modelgrouptemplate_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='modelgrouptemplate',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='modeltemplate',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
    ]
