# Generated by Django 4.1.7 on 2023-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_alter_connectiontemplate_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='execution_protocol',
            field=models.IntegerField(choices=[('ssh', 'SSH'), ('http', 'HTTP')], default=1, help_text='The network protocol that will be used to execute connection template (SSH / HTTP(S)).', verbose_name='Execution protocol'),
        ),
    ]
