# Generated by Django 4.1.7 on 2023-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_alter_connectiontemplate_execution_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='execution_protocol',
            field=models.IntegerField(choices=[(1, 'SSH'), (2, 'HTTP')], default=1, help_text='The network protocol that will be used to execute connection template (SSH / HTTP(S)).', verbose_name='Execution protocol'),
        ),
        migrations.AlterField(
            model_name='connectiontemplate',
            name='response_type',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'List'), (3, 'Dict'), (4, 'String')], default=1, help_text='Xxx.', verbose_name='Type of response'),
        ),
    ]
