# Generated by Django 4.1.7 on 2023-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_alter_connectiontemplate_execution_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='execution_protocol',
            field=models.IntegerField(choices=[(1, 'SSH'), (2, 'HTTP(S)'), (3, 'Discovery')], default=1, help_text='The network protocol that will be used to execute connection template (SSH / HTTP(S)).', verbose_name='Execution protocol'),
        ),
        migrations.AlterField(
            model_name='connectiontemplate',
            name='http_method',
            field=models.IntegerField(choices=[(1, 'Get HTTP(S) method'), (2, 'Post HTTP(S) method'), (3, 'Put HTTP(S) method'), (4, 'Delete HTTP(S) method')], default=1, help_text='Type of HTTP request method (GET, POST, PUT, DELETE).', verbose_name='HTTP(S) request method'),
        ),
        migrations.AlterField(
            model_name='connectiontemplate',
            name='response_type',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'List'), (2, 'Dict'), (3, 'String')], default=1, help_text='Xxx.', verbose_name='Type of response'),
        ),
        migrations.AlterField(
            model_name='connectiontemplate',
            name='ssh_type',
            field=models.IntegerField(choices=[(1, 'SSH command'), (2, 'SSH command template')], default=1, help_text='Type of SSH connection template (Command / template).', verbose_name='SSH execution type'),
        ),
    ]
