# Generated by Django 4.1.7 on 2023-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0017_alter_connectiontemplate_execution_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontemplate',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='modelgrouptemplate',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='modeltemplate',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
