# Generated by Django 4.1.4 on 2023-03-05 09:37

import autocli2.base.validators.base_validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DataTimeModel create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='DataTimeModel last update date.', verbose_name='Updated')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'IdentificationModel with this name already exists.'}, help_text='IdentificationModel name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name')),
                ('slug', models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=64, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='IdentificationModel default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='IdentificationModel description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description')),
                ('ico', models.IntegerField(default=1, help_text='IdentificationModel graphical representation.', verbose_name='IdentificationModel ico')),
                ('is_current', models.BooleanField(default=True, help_text='Xxx', verbose_name='Current global settings')),
                ('notification_level', models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], default=4, help_text='The level of severity of the performed action.', verbose_name='Notification severity level')),
                ('logger_level', models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], default=1, help_text='The level of severity of the performed action.', verbose_name='Logger severity level')),
            ],
            options={
                'verbose_name': 'Global setting',
                'verbose_name_plural': 'Global settings',
            },
        ),
        migrations.CreateModel(
            name='AdministratorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DataTimeModel create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='DataTimeModel last update date.', verbose_name='Updated')),
                ('administrator', models.ForeignKey(blank=True, help_text='Administrator responsible for provided AdministratorModel.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('default_credentials', models.ForeignKey(help_text='The following credentials will be used by default when connecting via SSH / HTTP.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Default SSH credentials')),
            ],
            options={
                'verbose_name': 'Administrator setting',
                'verbose_name_plural': 'Administrator settings',
            },
        ),
    ]
