# Generated by Django 4.1.7 on 2023-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='default_password',
            field=models.CharField(default='!Cisco@12345', help_text='Default password used to connect to hosts.', max_length=128, verbose_name='Default password'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='default_user',
            field=models.CharField(default='admin', help_text='Default username used to connect to hosts.', max_length=128, verbose_name='Default username'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='http_timeout',
            field=models.IntegerField(default=10, help_text='The HTTP(S) timeout refers to the time that an AutoCli 2 application waits for a response to an HTTP(S) request before closing the connection.', verbose_name='HTTP session timeout'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Active settings template used by the AutoCli 2 application', verbose_name='Current global settings'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='ssh_timeout',
            field=models.IntegerField(default=10, help_text='The SSH timeout refers to the time that an AutoCli 2 application waits for a response to an SSH request before closing the connection.', verbose_name='SSH session timeout'),
        ),
    ]
