# Generated by Django 4.1.4 on 2023-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='default_password',
            field=models.CharField(default='!Cisco123', help_text='Xxx.', max_length=128, verbose_name='Default password'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='default_user',
            field=models.CharField(default='admin', help_text='Xxx.', max_length=128, verbose_name='Default username'),
        ),
    ]
