# Generated by Django 4.1.7 on 2023-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministratorSetting',
        ),
    ]
