# Generated by Django 4.1.7 on 2023-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ssh_repeat',
            field=models.IntegerField(default=2, help_text='The SSH repeat connection refers to the number of repeats that the application will make in case the previous one fails.', verbose_name='SSH repeat connection'),
        ),
    ]
