# Generated by Django 4.1.4 on 2023-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Xxx', verbose_name='Current global settings'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='logger_level',
            field=models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], default=0, help_text='The level of severity of the performed action.', verbose_name='Logger severity level'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='notification_level',
            field=models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], default=0, help_text='The level of severity of the performed action.', verbose_name='Notification severity level'),
        ),
    ]
