# Generated by Django 4.1.4 on 2023-03-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_globalsetting_default_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsetting',
            name='slug',
        ),
    ]
