# Generated by Django 4.1.7 on 2023-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_globalsetting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='http_timeout',
            field=models.IntegerField(default=1, help_text='Xxx.', verbose_name='HTTP session timeout'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='ssh_timeout',
            field=models.IntegerField(default=1, help_text='Xxx.', verbose_name='SSH session timeout'),
        ),
    ]
