# Generated by Django 4.1.7 on 2023-03-19 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_globalsetting_http_timeout_globalsetting_ssh_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, help_text='IdentificationModel name representation (Slug).', max_length=512, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
