# Generated by Django 4.1.7 on 2023-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_globalsetting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
    ]
