# Generated by Django 4.1.7 on 2023-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_globalsetting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorsetting',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='http_timeout',
            field=models.IntegerField(default=10, help_text='Xxx.', verbose_name='HTTP session timeout'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='ssh_timeout',
            field=models.IntegerField(default=10, help_text='Xxx.', verbose_name='SSH session timeout'),
        ),
    ]
