# Generated by Django 4.1.7 on 2023-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_administratorsetting_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorsetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='administratorsetting',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='administratorsetting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='administratorsetting',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
    ]
