# Generated by Django 4.1.7 on 2023-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_administratorsetting_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='logger_level',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Error'), (3, 'Warning'), (4, 'Info'), (5, 'Debug')], default=1, help_text='The level of severity of the performed action.', verbose_name='Logger severity level'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='notification_level',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Error'), (3, 'Warning'), (4, 'Info'), (5, 'Debug')], default=4, help_text='The level of severity of the performed action.', verbose_name='Notification severity level'),
        ),
    ]
