# Generated by Django 4.1.7 on 2023-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_globalsetting_logger_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
