# Generated by Django 4.1.4 on 2022-12-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time of the change creation.', verbose_name='Timestamp')),
                ('type', models.IntegerField(choices=[(0, '---'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The type of action that was performed on a given model.', verbose_name='Type of action')),
                ('severity', models.IntegerField(choices=[(0, '---'), (1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], default=0, help_text='Severity level of notification message.', verbose_name='Notification severity')),
                ('task_id', models.CharField(blank=True, help_text='ID of the associated task.', max_length=64, null=True, verbose_name='Task ID')),
                ('app_name', models.CharField(blank=True, help_text='Name of the object application.', max_length=64, null=True, verbose_name='Object application name')),
                ('model_name', models.CharField(blank=True, help_text='Name of the object model.', max_length=64, null=True, verbose_name='Object model name')),
                ('object_id', models.IntegerField(blank=True, help_text='Correlated object ID representation.', null=True, verbose_name='Object ID')),
                ('application', models.CharField(help_text='Name of the application which triggered the notification.', max_length=64, verbose_name='Application')),
                ('message', models.CharField(help_text='Notification message.', max_length=256, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-pk'],
            },
        ),
    ]
