# Generated by Django 4.1.4 on 2023-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='api_pagination',
            field=models.BooleanField(default=False, help_text='When the pagination value is active, the API request will be repeated to collect all objects from all paginated pages.', verbose_name='API pagination'),
        ),
    ]
