# Generated by Django 4.1.4 on 2023-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='http_port',
            field=models.IntegerField(default=443, help_text='Xxx.', verbose_name='HTTP/S port'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=22, help_text='Xxx.', verbose_name='SSH port'),
        ),
    ]
