# Generated by Django 4.1.7 on 2023-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_platform_http_data_path_platform_http_default_header_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='platform',
            name='ssh_platform_type',
            field=models.CharField(choices=[('generic', 'Generic Device'), ('cisco_asa', 'Cisco ASA'), ('cisco_ios', 'Cisco IOS'), ('cisco_xe', 'Cisco IOS XE'), ('cisco_nxos', 'Cisco NXOS'), ('cisco_xr', 'Cisco IOS XR'), ('cisco_viptela', 'Cisco SD-WAN'), ('cisco_wlc', 'Cisco WLC'), ('cisco_wlc_85', 'Cisco WLC 85'), ('alcatel_aos', 'Alcatel AOS'), ('alcatel_sros', 'Alcatel SROS'), ('apresia_aeos', 'Apresia AEOS'), ('arista_eos', 'Arista EOS'), ('ciena_saos', 'Ciena SAOS'), ('dell_force10', 'Dell Force10'), ('dell_os9', 'Dell OS9'), ('dell_os10', 'Dell OS10'), ('dell_powerconnect', 'Dell Powerconnect'), ('f5_tmsh', 'F5 Tmsh'), ('f5_linux', 'F5 Linux'), ('hp_comware', 'Hp Comware'), ('huawei', 'Huawei'), ('juniper_junos', 'Juniper Junos'), ('linux', 'Linux'), ('ericsson_ipos', 'Ericsson IPOS'), ('extreme_exos', 'Extreme EXOS'), ('extreme_netiron', 'Extreme Netiron'), ('extreme_slx', 'Extreme SLX'), ('extreme_tierra', 'Extreme Tierra'), ('mikrotik_routeros', 'MikroTik Router OS'), ('mikrotik_switchos', 'MikroTik Switch OS'), ('ubiquiti_edgeswitch', 'Ubiquiti Edgeswitch'), ('ubiquiti_edge', 'Ubiquiti Edge'), ('ubiquiti_edgerouter', 'Ubiquiti Edge Router'), ('mellanox_mlnxos', 'Mellanox Mlnxos'), ('yamaha', 'Yamaha'), ('fortinet', 'Fortinet'), ('paloalto_panos', 'Paloalto Panos'), ('supermicro_smis', 'Supermicro Smis'), ('flexvnf', 'Flexvnf')], default='generic', help_text='Netmiko platform type (SSH only).', max_length=32, verbose_name='Netmiko platform type'),
        ),
        migrations.RemoveField(
            model_name='platform',
            name='ssh_device_type',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='ssh_invalid_responses',
        ),
    ]
