# Generated by Django 4.1.4 on 2023-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_host_http_port_host_ssh_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisetting',
            name='api_pagination_key',
        ),
        migrations.RemoveField(
            model_name='apisetting',
            name='api_pagination_path',
        ),
        migrations.RemoveField(
            model_name='apisetting',
            name='api_token_key_name',
        ),
        migrations.RemoveField(
            model_name='apisetting',
            name='api_token_key_value',
        ),
        migrations.RemoveField(
            model_name='apisetting',
            name='default_api_header',
        ),
        migrations.RemoveField(
            model_name='apisetting',
            name='default_api_params',
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_default_header',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='API default heder'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_default_params',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='API default parameters'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_next_page_code_path',
            field=models.JSONField(blank=True, help_text='The next page path value is used by the connection template when the API request returns a response, that is divided into many pages (paginated response). In this case next page path value is used to retrieve the pagination code required to prepare the next API request for other pages (The value will only be used if the pagination field is enabled).', null=True, verbose_name='API next page code path'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_next_page_link_path',
            field=models.JSONField(blank=True, help_text='The next page path value is used by the connection template when the API request returns a response that is divided into many pages (paginated response). In this case, the next page path value is used to retrieve the pagination URL link used in the next API request for other pages (The value will only be used if the pagination field is enabled).', null=True, verbose_name='API next page link path'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_pagination',
            field=models.BooleanField(default=True, help_text='When the pagination value is active, the API request will be repeated to collect all objects from all paginated pages.', verbose_name='API pagination'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_pagination_param_key',
            field=models.CharField(blank=True, help_text='Information collected based on the next page code path value is added to the URL with a specific code. This code should be provided as a pagination param key value. For example, the value "cursor" will be added to the URL in the form "?cursor={{next page code}}" (The value will only be used if the pagination field is enabled).', max_length=128, null=True, verbose_name='API pagination param key'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_token_heder_key',
            field=models.CharField(blank=True, help_text='When authenticating an API connection using an API         token, the token header key value defines the API request header key. In the example "Authorization=APIToken {{key}}", the token header key value is Authorization.', max_length=128, null=True, verbose_name='API token heder key'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='api_token_heder_value',
            field=models.CharField(blank=True, help_text='When authenticating an API connection using an API token, the token header value defines the API request header key. In the example "Authorization=APIToken {{key}}", the token header value is APIToken.', max_length=128, null=True, verbose_name='API token heder value'),
        ),
        migrations.AlterField(
            model_name='apisetting',
            name='api_data_path',
            field=models.JSONField(blank=True, help_text='The data path value is used to collect useful data included in the API response.', null=True, verbose_name='API data path'),
        ),
    ]
