# Generated by Django 4.1.4 on 2023-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_platform_api_pagination'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='data_collection_protocol',
            field=models.IntegerField(choices=[(1, 'SSH'), (2, 'HTTP')], default=1, help_text='The network protocol that will be used to execute connection template (SSH / HTTP(S)).', verbose_name='Data collection protocol'),
        ),
    ]
