# Generated by Django 4.1.4 on 2023-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_apisetting_api_pagination_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Xxx.', max_length=32, null=True, verbose_name='Region code'),
        ),
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, help_text='Xxx.', max_length=32, null=True, verbose_name='Site code'),
        ),
    ]
