# Generated by Django 4.1.4 on 2023-03-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_host_data_collection_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='host',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
    ]
