# Generated by Django 4.1.4 on 2023-03-11 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_credential_slug_remove_host_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='credential',
            field=models.ForeignKey(default=1, help_text='Credentials.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credentials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='platform',
            field=models.ForeignKey(default=1, help_text='Software.', on_delete=django.db.models.deletion.PROTECT, to='inventory.platform', verbose_name='Software'),
            preserve_default=False,
        ),
    ]
