# Generated by Django 4.1.4 on 2023-03-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_host_certificate_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_deleted',
        ),
    ]
