# Generated by Django 4.1.7 on 2023-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_credential_slug_host_slug_platform_slug_region_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='host',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=512, unique=True, verbose_name='Slug'),
        ),
    ]
