# Generated by Django 4.1.7 on 2023-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_credential_slug_alter_host_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='data_collection_protocol',
            field=models.CharField(choices=[('ssh', 'SSH'), ('http', 'HTTP')], default='ssh', help_text='The network protocol that will be used to execute connection template (SSH / HTTP(S)).', max_length=8, verbose_name='Data collection protocol'),
        ),
    ]
