# Generated by Django 4.1.7 on 2023-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_credential_is_deleted_host_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='host',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='host',
            name='data_collection_protocol',
            field=models.CharField(choices=[(None, 'Empty'), ('HTTP', 'HTTP(S)'), ('SSH', 'SSH'), ('DS', 'Discovery')], help_text='The network protocol that will be used to execute connection template (SSH / HTTP(S)).', max_length=4, verbose_name='Data collection protocol'),
        ),
        migrations.AlterField(
            model_name='host',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='host',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='host',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Base model create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is Base model active (Inactive Base model has limited functionality).', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is Base model root (Root Base model cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Base model last update date.', verbose_name='Updated'),
        ),
    ]
