# Generated by Django 4.1.7 on 2023-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_credential_slug_alter_host_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(help_text='Valid IP address or domain name used to establish the SSH / HTTP(S) connections.', max_length=128, unique=True, verbose_name='Hostname'),
        ),
    ]
