# Generated by Django 4.1.4 on 2023-03-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(error_messages={'blank': 'Notification message field is mandatory.', 'invalid': 'Enter a valid Notification message. It must contain 1 to 1024 digits.', 'null': 'Notification message field is mandatory.'}, help_text='Notification message.', max_length=1024, verbose_name='Message'),
        ),
    ]
