# Generated by Django 4.1.4 on 2023-02-05 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='administrator',
            field=models.ForeignKey(blank=True, help_text='Administrator responsible for provided object.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='administrator',
            field=models.ForeignKey(blank=True, help_text='Administrator responsible for provided object.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='severity',
            field=models.IntegerField(choices=[(1, 'CRITICAL'), (2, 'ERROR'), (3, 'WARNING'), (4, 'INFO'), (5, 'DEBUG')], default=0, help_text='The level of severity of the performed action.', verbose_name='Severity level'),
        ),
    ]
