# Generated by Django 4.1.7 on 2023-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(error_messages={'invalid': 'Enter a valid Notification message. It must contain 1 to 1024 digits.'}, help_text='Notification message.', max_length=1024, verbose_name='Message'),
        ),
    ]
