# Generated by Django 4.1.4 on 2023-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Log execution time.', null=True, verbose_name='Execution time'),
        ),
    ]
