# Generated by Django 4.1.7 on 2023-04-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_changelog_object_url_notification_object_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='object_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_url',
        ),
    ]
