# Generated by Django 4.1.7 on 2023-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The type of action that was performed on the object.', verbose_name='Type of action'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The type of action that was performed on the object.', verbose_name='Type of action'),
        ),
    ]
