# Generated by Django 4.1.7 on 2023-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_changelog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
    ]
