# Generated by Django 4.1.7 on 2023-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_changelog_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The type of action that was performed on the object.', verbose_name='Type of action'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The type of action that was performed on the object.', verbose_name='Type of action'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'Error'), (3, 'Warning'), (4, 'Info'), (5, 'Debug')], default=0, help_text='The level of severity of the performed action.', verbose_name='Severity level'),
        ),
    ]
