# Generated by Django 4.1.4 on 2023-02-05 18:18

import autocli2.base.validators.base_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Object description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description')),
                ('ico', models.IntegerField(default=1, help_text='Object graphical representation.', verbose_name='Object ico')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
                ('execution_method', models.IntegerField(choices=[(1, 'SSH'), (2, 'HTTPS')], default=1, help_text='Method of template execution (SSH / HTTPS).', verbose_name='Execution method')),
                ('ssh_type', models.IntegerField(choices=[(1, 'Command'), (2, 'template')], default=1, help_text='Type of SSH execution (Command / template).', verbose_name='SSH execution type')),
                ('ssh_command', models.CharField(blank=True, help_text='Xxx.', max_length=128, null=True, verbose_name='Xxx')),
                ('ssh_fsm', models.TextField(help_text='Xxx.', verbose_name='Xxx')),
                ('https_method', models.IntegerField(choices=[(1, 'Get'), (2, 'Post'), (3, 'Put'), (4, 'Delete')], default=1, help_text='Xx (HTTPS request methods).', verbose_name='HTTPS method')),
                ('https_url', models.CharField(blank=True, help_text='Xxx.', max_length=128, null=True, verbose_name='Xxx')),
                ('https_header', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTPS heder')),
                ('https_params', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTPS parameters')),
                ('https_body', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTPS body')),
                ('https_pagination', models.BooleanField(default=False, help_text='Xxx.', verbose_name='Xxx')),
                ('https_pagination_path', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTPS body')),
                ('certificate', models.BooleanField(default=False, help_text='Xxx.', verbose_name='Xxx')),
            ],
            options={
                'verbose_name': 'Connection template',
                'verbose_name_plural': 'Connection templates',
            },
        ),
    ]
