# Generated by Django 4.1.4 on 2023-02-05 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontemplate',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, help_text='Object name representation (Slug).', max_length=64, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
