# Generated by Django 4.1.4 on 2023-02-06 19:47

import autocli2.base.validators.base_validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_connectiontemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name')),
                ('slug', models.CharField(help_text='Object name representation (Slug).', max_length=64, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Object description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description')),
                ('ico', models.IntegerField(default=1, help_text='Object graphical representation.', verbose_name='Object ico')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Connection group',
                'verbose_name_plural': 'Connection groups',
            },
        ),
        migrations.CreateModel(
            name='ConnectionSshTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
                ('template', models.TextField(help_text='Xxx.', verbose_name='Xxx')),
                ('sfm_expression', models.TextField(help_text='Xxx.', verbose_name='Xxx')),
                ('regex_expression', models.TextField(help_text='Xxx.', verbose_name='Xxx')),
            ],
            options={
                'verbose_name': 'SSH connection template',
                'verbose_name_plural': 'SSH connection templates',
            },
        ),
        migrations.CreateModel(
            name='DataGroupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
                ('keys', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='Keys')),
                ('keys_regex', models.CharField(blank=True, help_text='Xxx.', max_length=128, null=True, verbose_name='Xxx')),
                ('connection_template', models.ForeignKey(blank=True, help_text='Connection template.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.connectiontemplate', verbose_name='Connection template')),
            ],
            options={
                'verbose_name': 'Data group template',
                'verbose_name_plural': 'Data group templates',
            },
        ),
        migrations.CreateModel(
            name='ModelGroupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name')),
                ('slug', models.CharField(help_text='Object name representation (Slug).', max_length=64, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Object description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description')),
                ('ico', models.IntegerField(default=1, help_text='Object graphical representation.', verbose_name='Object ico')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Model group template',
                'verbose_name_plural': 'Model group templates',
            },
        ),
        migrations.CreateModel(
            name='ModelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name')),
                ('slug', models.CharField(help_text='Object name representation (Slug).', max_length=64, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Object description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description')),
                ('ico', models.IntegerField(default=1, help_text='Object graphical representation.', verbose_name='Object ico')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
                ('model_group_template', models.ForeignKey(blank=True, help_text='Model group template.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.modelgrouptemplate', verbose_name='Model group template')),
            ],
            options={
                'verbose_name': 'Model template',
                'verbose_name_plural': 'Model templates',
            },
        ),
        migrations.CreateModel(
            name='DataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
                ('path', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='Path')),
                ('data_group_template', models.ForeignKey(blank=True, help_text='Data group template.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.datagrouptemplate', verbose_name='Data group template')),
                ('model_template', models.ForeignKey(blank=True, help_text='Model template.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.modeltemplate', verbose_name='Model template')),
            ],
            options={
                'verbose_name': 'Data template',
                'verbose_name_plural': 'Data templates',
            },
        ),
        migrations.AddField(
            model_name='datagrouptemplate',
            name='model_group_template',
            field=models.ForeignKey(blank=True, help_text='Model group template.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.modelgrouptemplate', verbose_name='Model group template'),
        ),
        migrations.AddField(
            model_name='connectiontemplate',
            name='connection_ssh_template',
            field=models.ForeignKey(blank=True, help_text='SSH template.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.connectionsshtemplate', verbose_name='SSH template'),
        ),
        migrations.AddField(
            model_name='connectiontemplate',
            name='connection_template_group',
            field=models.ForeignKey(blank=True, help_text='Connection template group.', null=True, on_delete=django.db.models.deletion.PROTECT, to='connectors.connectiongroup', verbose_name='Connection template group'),
        ),
    ]
