# Generated by Django 4.1.4 on 2023-02-13 21:09

import autocli2.base.validators.base_validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('administrator', models.ForeignKey(blank=True, help_text='Administrator responsible for provided object.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Object name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name')),
                ('slug', models.CharField(help_text='Object name representation (Slug).', max_length=64, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='Object default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Object description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description')),
                ('ico', models.IntegerField(default=1, help_text='Object graphical representation.', verbose_name='Object ico')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is object deleted (Deleted object is reserved for backward compatibility).', verbose_name='Deleted')),
                ('is_root', models.BooleanField(default=False, help_text='Is object root (Root object cannot be deleted or modify).', verbose_name='Root')),
                ('is_active', models.BooleanField(default=True, help_text='Is object active (Inactive object has limited functionality).', verbose_name='Active')),
                ('execution_protocol', models.IntegerField(choices=[(1, 'SSH'), (2, 'HTTP')], default=1, help_text='Network protocol used to execute the connection template (SSH / HTTP).', verbose_name='Execution protocol')),
                ('executor_type', models.IntegerField(choices=[(1, 'Task'), (2, 'Template/s')], default=1, help_text='Xxx.', verbose_name='Xxx')),
                ('task', models.IntegerField(choices=[(1, 'Task one'), (2, 'Task Two')], default=0, help_text='Xxx.', verbose_name='Xxx')),
                ('task_argumants', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='Xxx')),
                ('task_id', models.CharField(blank=True, help_text='Xxx.', max_length=128, null=True, verbose_name='Xxx')),
                ('status', models.IntegerField(choices=[(1, 'Initiation'), (2, 'Execution'), (3, 'Executed')], default=0, help_text='Xxx.', verbose_name='Xxx')),
                ('output', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='Xxx')),
                ('results', models.BooleanField(default=False, help_text='Xxx.', verbose_name='Xxx')),
                ('administrator', models.ForeignKey(blank=True, help_text='Administrator responsible for provided object.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('connection_templates', models.ManyToManyField(blank=True, help_text='Xxx.', null=True, to='connector.connectiontemplate', verbose_name='Xxx')),
                ('credential', models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Xxx')),
                ('hosts', models.ManyToManyField(blank=True, help_text='Xxx.', null=True, to='inventory.host', verbose_name='Xxx')),
            ],
            options={
                'verbose_name': 'Executor',
                'verbose_name_plural': 'Executors',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('result_status', models.BooleanField(default=False, help_text='A positive result means that the command output was successfully received and processed.', verbose_name='Result status')),
                ('ssh_raw_data_status', models.BooleanField(default=False, help_text='A positive result means that the raw data collection process has been successfully completed.', verbose_name='Raw data status')),
                ('ssh_processed_data_status', models.BooleanField(default=False, help_text='A positive result means that the process of processing the data was completed successfully.', verbose_name='Processed data status')),
                ('ssh_raw_data', models.TextField(blank=True, help_text='CLI command raw data output.', null=True, verbose_name='Command raw data')),
                ('ssh_processed_data', models.JSONField(blank=True, help_text='CLI command FSM process data.', null=True, verbose_name='Command processed data')),
                ('https_response_status', models.BooleanField(default=False, help_text='Xxx.', verbose_name='Xxx')),
                ('https_response_code', models.IntegerField(default=0, help_text='Xxx.', verbose_name='Xxx')),
                ('https_response', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTP heder')),
                ('connection_templates', models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='connector.connectiontemplate', verbose_name='Xxx')),
                ('credential', models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Xxx')),
                ('executor', models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='executor.executor', verbose_name='Xxx')),
                ('hosts', models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.host', verbose_name='Xxx')),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
            },
        ),
        migrations.CreateModel(
            name='ConvertedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='object last update date.', verbose_name='Updated')),
                ('value', models.CharField(blank=True, help_text='Xxx.', max_length=128, null=True, verbose_name='Value')),
                ('json_value', models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='JSON value')),
                ('data_template', models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='connector.datatemplate', verbose_name='Xxx')),
                ('execution', models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='executor.execution', verbose_name='Xxx')),
                ('snapshot', models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='executor.snapshot', verbose_name='Xxx')),
            ],
            options={
                'verbose_name': 'Converted data',
                'verbose_name_plural': 'Converted data',
            },
        ),
    ]
