# Generated by Django 4.1.4 on 2023-02-26 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_host_http_port_host_ssh_port'),
        ('connector', '0001_initial'),
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executor',
            old_name='task_argumants',
            new_name='task_arguments',
        ),
        migrations.AlterField(
            model_name='execution',
            name='connection_templates',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='connector.connectiontemplate', verbose_name='Connection templates'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='credential',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credential'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='executor',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='executor.executor', verbose_name='Executor'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='hosts',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.host', verbose_name='Hosts'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTP/S response'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response_code',
            field=models.IntegerField(default=0, help_text='Xxx.', verbose_name='HTTP/S response code'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response_status',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='HTTP/S response status'),
        ),
    ]
