# Generated by Django 4.1.7 on 2023-03-26 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connector', '0002_initial'),
        ('inventory', '0001_initial'),
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='administrator',
            field=models.ForeignKey(blank=True, help_text='Administrator responsible for provided AdministratorModel.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.AddField(
            model_name='executor',
            name='administrator',
            field=models.ForeignKey(blank=True, help_text='Administrator responsible for provided AdministratorModel.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.AddField(
            model_name='executor',
            name='connection_templates',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='connector.connectiontemplate', verbose_name='Connection templates'),
        ),
        migrations.AddField(
            model_name='executor',
            name='hosts',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='inventory.host', verbose_name='Hosts'),
        ),
        migrations.AddField(
            model_name='execution',
            name='connection_template',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='connector.connectiontemplate', verbose_name='Connection templates'),
        ),
        migrations.AddField(
            model_name='execution',
            name='credential',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credential'),
        ),
        migrations.AddField(
            model_name='execution',
            name='executor',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='executor.executor', verbose_name='Executor'),
        ),
        migrations.AddField(
            model_name='execution',
            name='host',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.host', verbose_name='Hosts'),
        ),
        migrations.AddField(
            model_name='converteddata',
            name='data_template',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='connector.datatemplate', verbose_name='Data template'),
        ),
        migrations.AddField(
            model_name='converteddata',
            name='execution',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='executor.execution', verbose_name='Execution'),
        ),
        migrations.AddField(
            model_name='converteddata',
            name='snapshot',
            field=models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='executor.snapshot', verbose_name='Snapshot'),
        ),
    ]
