# Generated by Django 4.1.7 on 2023-04-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
        ('executor', '0002_executor_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='executor_type',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='task',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='task_arguments',
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='data_template',
            field=models.ForeignKey(help_text='Related data template object based on which collected data was correlated.', on_delete=django.db.models.deletion.PROTECT, to='connector.datatemplate', verbose_name='Data template'),
        ),
    ]
