# Generated by Django 4.1.7 on 2023-03-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_alter_connectiontemplate_ssh_special_template'),
        ('inventory', '0003_remove_credential_tag_remove_host_tag_and_more'),
        ('executor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converteddata',
            name='data_template',
            field=models.ForeignKey(help_text='Related data template object basen on which collected data was corelated.', on_delete=django.db.models.deletion.PROTECT, to='connector.datatemplate', verbose_name='Data template'),
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='execution',
            field=models.ForeignKey(help_text='Related execution object from which collected data was taken.', on_delete=django.db.models.deletion.PROTECT, to='executor.execution', verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='json_value',
            field=models.JSONField(blank=True, help_text='JSON value collected from related execution object based on Data Template object.', null=True, verbose_name='JSON value'),
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='snapshot',
            field=models.ForeignKey(blank=True, help_text='Related snapshot object.', null=True, on_delete=django.db.models.deletion.PROTECT, to='executor.snapshot', verbose_name='Snapshot'),
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='value',
            field=models.CharField(blank=True, help_text='Value collected from related execution object based on Data Template object.', max_length=128, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='connection_template',
            field=models.ForeignKey(help_text='Related connection template object based on witch execution has been executed (Provides information about SSH / HTTP(S) command or URL executed on host).', on_delete=django.db.models.deletion.PROTECT, to='connector.connectiontemplate', verbose_name='Connection template'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='connection_template_representation',
            field=models.CharField(blank=True, help_text='Related connection template object representation.', max_length=128, null=True, verbose_name='Connection template representation'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='credential',
            field=models.ForeignKey(help_text='Related credential object used to authenticate connection to host.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credential'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='credential_representation',
            field=models.CharField(blank=True, help_text='Related credential object representation.', max_length=128, null=True, verbose_name='Credential representation'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='executor',
            field=models.ForeignKey(help_text='Related executor object that initiated the execution (Provides information about hosts, connection templates and execution type HTTP(S) / SSH).', on_delete=django.db.models.deletion.PROTECT, to='executor.executor', verbose_name='Executor'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='host',
            field=models.ForeignKey(help_text='Related host object on witch execution has been executed (Provides information such as host IP or domain name, platform, and credentials used to connect to the host).', on_delete=django.db.models.deletion.PROTECT, to='inventory.host', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='host_representation',
            field=models.CharField(blank=True, help_text='Related host object representation.', max_length=128, null=True, verbose_name='Host representation'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='http_response',
            field=models.JSONField(blank=True, help_text='Response received after HTTP(S) request was executed.', null=True, verbose_name='HTTP(S) response'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='http_response_code',
            field=models.IntegerField(blank=True, help_text='Response code received after HTTP(S) request was executed.', null=True, verbose_name='HTTP(S) response code'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='connection_templates',
            field=models.ManyToManyField(blank=True, help_text='Related connection template object based on witch execution will be executed (Provides information about SSH / HTTP(S) command or URL executed on host).', to='connector.connectiontemplate', verbose_name='Connection templates'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='executor_type',
            field=models.IntegerField(choices=[(1, 'Task'), (2, 'Template/s')], default=1, help_text='Execution type (HTTP(S) or SSH).', verbose_name='Executor type'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='hosts',
            field=models.ManyToManyField(blank=True, help_text='Related hosts objects on witch execution will be executed (Provides information such as host IP or domain name, platform, and credentials used to connect to the host).', to='inventory.host', verbose_name='Hosts'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task',
            field=models.IntegerField(choices=[(1, 'Collect host/s data'), (2, 'Check host/s status')], default=0, help_text='Task that will be executed.', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task_arguments',
            field=models.JSONField(blank=True, help_text='Task arguments used to run task.', null=True, verbose_name='Task arguments'),
        ),
    ]
