# Generated by Django 4.1.4 on 2023-03-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_platform_api_pagination'),
        ('executor', '0002_remove_executor_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credential'),
        ),
    ]
