# Generated by Django 4.1.4 on 2023-02-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_host_http_port_host_ssh_port'),
        ('connector', '0002_remove_connectiontemplate_connection_template_groups_and_more'),
        ('executor', '0002_rename_task_argumants_executor_task_arguments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='connection_templates',
            field=models.ManyToManyField(help_text='Xxx.', to='connector.connectiontemplate', verbose_name='connection_templates'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='credential',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='credential'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='hosts',
            field=models.ManyToManyField(help_text='Xxx.', to='inventory.host', verbose_name='hosts'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='output',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='output'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='results',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='results'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiation'), (2, 'Execution'), (3, 'Executed')], default=0, help_text='Xxx.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task',
            field=models.IntegerField(choices=[(1, 'Task one'), (2, 'Task Two')], default=0, help_text='Xxx.', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task_arguments',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='task_arguments'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task_id',
            field=models.CharField(blank=True, help_text='Xxx.', max_length=128, null=True, verbose_name='task_id'),
        ),
    ]
