# Generated by Django 4.1.4 on 2023-03-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_executor_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='credential',
        ),
    ]
