# Generated by Django 4.1.4 on 2023-03-01 13:10

import autocli2.base.validators.base_validator
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_alter_executor_connection_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='description',
            field=models.CharField(blank=True, default='IdentificationModel default description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='IdentificationModel description.', max_length=256, null=True, validators=[autocli2.base.validators.base_validator.DescriptionValueValidator()], verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='ico',
            field=models.IntegerField(default=1, help_text='IdentificationModel graphical representation.', verbose_name='IdentificationModel ico'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is StatusModel active (Inactive StatusModel has limited functionality).', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is StatusModel deleted (Deleted StatusModel is reserved for backward compatibility).', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='is_root',
            field=models.BooleanField(default=False, help_text='Is StatusModel root (Root StatusModel cannot be deleted or modify).', verbose_name='Root'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 64 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'IdentificationModel with this name already exists.'}, help_text='IdentificationModel name.', max_length=64, unique=True, validators=[autocli2.base.validators.base_validator.NameValueValidator()], verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, help_text='IdentificationModel name representation (Slug).', max_length=64, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
