# Generated by Django 4.1.4 on 2023-03-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_remove_executor_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='execution_protocol',
        ),
    ]
