# Generated by Django 4.1.4 on 2023-03-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_apisetting_api_pagination_key_and_more'),
        ('connector', '0003_alter_datagrouptemplate_keys_regex'),
        ('executor', '0004_snapshot_description_snapshot_ico_snapshot_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='data_template',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='connector.datatemplate', verbose_name='Data template'),
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='execution',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='executor.execution', verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='converteddata',
            name='snapshot',
            field=models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='executor.snapshot', verbose_name='Snapshot'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTP(S) response'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response_code',
            field=models.IntegerField(default=0, help_text='Xxx.', verbose_name='HTTP(S) response code'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response_status',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='HTTP(S) response status'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='connection_templates',
            field=models.ManyToManyField(help_text='Xxx.', to='connector.connectiontemplate', verbose_name='Connection templates'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='credential',
            field=models.ForeignKey(help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credential'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='executor_type',
            field=models.IntegerField(choices=[(1, 'Task'), (2, 'Template/s')], default=1, help_text='Xxx.', verbose_name='Executor type'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='hosts',
            field=models.ManyToManyField(help_text='Xxx.', to='inventory.host', verbose_name='Hosts'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='output',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='results',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiation'), (2, 'Execution'), (3, 'Executed')], default=0, help_text='Xxx.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task',
            field=models.IntegerField(choices=[(1, 'Task one'), (2, 'Task Two')], default=0, help_text='Xxx.', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='task_arguments',
            field=models.JSONField(blank=True, help_text='Xxx.', null=True, verbose_name='Task arguments'),
        ),
    ]
