# Generated by Django 4.1.4 on 2023-03-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_apisetting_api_pagination_key_and_more'),
        ('connector', '0003_alter_datagrouptemplate_keys_regex'),
        ('executor', '0005_remove_executor_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='connection_templates',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='connector.connectiontemplate', verbose_name='Connection templates'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.credential', verbose_name='Credential'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='hosts',
            field=models.ManyToManyField(blank=True, help_text='Xxx.', to='inventory.host', verbose_name='Hosts'),
        ),
    ]
