# Generated by Django 4.1.4 on 2023-03-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0006_execution_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='hosts',
            new_name='host',
        ),
    ]
