# Generated by Django 4.1.4 on 2023-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0008_rename_connection_templates_execution_connection_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='ssh_response_status',
            field=models.BooleanField(default=False, help_text='Xxx.', verbose_name='HTTP(S) response status'),
        ),
    ]
