# Generated by Django 4.1.4 on 2023-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0012_remove_executor_output_remove_executor_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='slug',
        ),
        migrations.AlterField(
            model_name='executor',
            name='task',
            field=models.IntegerField(choices=[(1, 'Collect host/s data'), (2, 'Check host/s status')], default=0, help_text='Xxx.', verbose_name='Task'),
        ),
    ]
