# Generated by Django 4.1.4 on 2023-03-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0013_remove_executor_slug_remove_snapshot_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='https_response_status',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='ssh_response_status',
        ),
    ]
