# Generated by Django 4.1.4 on 2023-03-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0014_remove_execution_https_response_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='is_deleted',
        ),
    ]
