# Generated by Django 4.1.4 on 2023-03-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_credential_is_deleted_remove_host_is_deleted_and_more'),
        ('executor', '0015_remove_executor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='host',
            field=models.ForeignKey(default=1, help_text='Xxx.', on_delete=django.db.models.deletion.PROTECT, to='inventory.host', verbose_name='Hosts'),
            preserve_default=False,
        ),
    ]
