# Generated by Django 4.1.7 on 2023-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0016_snapshot_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='host',
        ),
        migrations.AlterField(
            model_name='execution',
            name='https_response_code',
            field=models.IntegerField(blank=True, help_text='Xxx.', null=True, verbose_name='HTTP(S) response code'),
        ),
    ]
