# Generated by Django 4.1.7 on 2023-03-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0017_remove_snapshot_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='https_response',
            new_name='http_response',
        ),
        migrations.RenameField(
            model_name='execution',
            old_name='https_response_code',
            new_name='http_response_code',
        ),
    ]
