# Generated by Django 4.1.7 on 2023-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0020_alter_executor_slug_alter_snapshot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='converteddata',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='execution',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='executor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is Base model object deleted.', verbose_name='Deleted'),
        ),
    ]
