# Generated by Django 4.1.7 on 2023-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0022_converteddata_is_active_converteddata_is_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='slug',
            field=models.CharField(help_text='IdentificationModel name representation (Slug).', max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
